# Service Account for MySQL
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa

---

# PersistentVolumeClaim for MySQL Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql-sa
      automountServiceAccountToken: false
      containers:
        - name: mysql
          image: mysql:8.0.30
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
            - name: MYSQL_DATABASE
              value: "mydatabase"
            - name: MYSQL_USER
              value: "springuser"
            - name: MYSQL_PASSWORD
              value: "springpass"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc

---

# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

---

# Service Account for Spring App
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-sa

---

# Spring Boot Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      serviceAccountName: spring-app-sa
      automountServiceAccountToken: false
      containers:
        - name: spring-app
          image: amineezzaouia07/amineezzaouia_5infini2:v1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/mydatabase?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "springuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "springpass"
          ports:
            - containerPort: 8087
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"

---

# Spring Boot Application Service
apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  type: LoadBalancer
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: spring-app
